### ISSUE TITLE
Figma remote MCP fails with "-32601 Method not found" in 1.1.21 (works in 1.1.9)

### ISSUE THREAD

**Issue by johannesloor** [github/app#3912]
## Summary

After updating the GitHub Copilot desktop app to 1.1.21 (macOS, arm64), the Figma remote MCP server
(`https://mcp.figma.com/mcp`, type `http`, OAuth) connects, completes OAuth, and is then dropped with
`MCP error -32601: Method not found`. The same `mcp-config.json`, OAuth registration and keychain token
work in app 1.1.9.

The difference is the bundled Copilot CLI runtime (the app logs `source=Bundled` for it at startup):

| App | Bundled runtime | Protocol negotiated with Figma | Result |
|---|---|---|---|
| 1.1.9 | Copilot CLI 1.0.79-9 | `2025-11-25` | tools load |
| 1.1.21 | Copilot CLI 1.0.84-5 | `2026-07-28` | `-32601 Method not found` ~0.5 s after `initialize`, server dropped |

Figma's server accepts protocol revision `2026-07-28` in the handshake but does not implement the new
methods that revision requires (`server/discover`, `subscriptions/listen`), so the runtime's first call
after `initialize` fails. The 1.0.79-9 runtime negotiated `2025-11-25` and worked; 1.0.84-5 treats the
failure as fatal instead of falling back to `2025-11-25`.

This matches the Copilot CLI 1.0.81 changelog entry "Ship MCP 2026-07-28 support to CLI, SDK, IDE, and
in-memory clients" (2026-08-27). Standalone CLI builds from 1.0.81 onward show the same behaviour, so
the fix most likely belongs in the shared runtime rather than the app. Related reports:
github/copilot-cli#4370 (aborts on `server/discover` errors), github/copilot-cli#4834 (2026-07-28
support incomplete), kjgpta/vectorsmith#28 (handshake change starting at CLI 1.0.81), and
github/app#1682 (earlier Figma remote MCP failures from the desktop app).

## Steps to reproduce

1. Install GitHub Copilot app 1.1.21 on macOS.
2. `~/.copilot/mcp-config.json`:
   ```json
   { "mcpServers": { "figma": { "type": "http", "url": "https://mcp.figma.com/mcp", "tools": ["*"] } } }
   ```
3. Open the app, complete the Figma OAuth flow when prompted.
4. Observe the Figma server shows as failed and no Figma tools are available.

## Expected

Figma tools are available, as in 1.1.9.

## Logs (`~/.copilot/logs/process-*.log`)

1.1.21 / runtime 1.0.84-5:
```
[INFO] [rust:rmcp::service] Service initialized as client {"peer_info":"Some(ServerPeerInfo { protocol_version: ProtocolVersion(\"2026-07-28\"), ... server_info: Some(Implementation { name: \"Figma MCP Server\", version: \"1.0.0\" ...
[WARNING] [rust:copilot_runtime::session::mcp::agent_host] MCP error -32601: Method not found. {"server":"figma"}
[ERROR] [rust:mcp_engine::session_authorizer] OAuth succeeded but MCP server reconnect failed {"server_name":"figma","error":"MCP error -32601: Method not found."}
```

Also seen intermittently during re-auth attempts on 1.1.21:
```
[ERROR] ... github_app::handlers::mcp_config: failed to start MCP OAuth login error=RPC error -32603: Request session.mcp.oauth.login failed with message: Client registration failed: server responded with status 403 Forbidden server_name=figma
```

1.1.9 / runtime 1.0.79-9 (same machine, same config, same token):
```
[INFO] [rust:rmcp::service] Service initialized as client {"peer_info":"Some(ServerPeerInfo { protocol_version: ProtocolVersion(\"2025-11-25\"), ... server_info: Some(Implementation { name: \"Figma MCP Server\", version: \"1.0.0\" ...
```
(no error follows; tools load)

## Environment

- GitHub Copilot app 1.1.21; works on 1.1.9
- macOS 26 (Darwin 25.6.0), Apple Silicon
- Figma remote MCP server, OAuth via dynamic client registration
- The GitHub remote MCP server (`github-mcp-server`) connects fine on 1.1.21 with the same `2026-07-28` negotiation, so the problem is specific to servers that advertise the new revision without implementing all of it

## Notes

- `COPILOT_CLI_PATH` is ignored in shipped builds, so the runtime cannot be swapped to test a fix.
- Suggested fix: when a server negotiates `2026-07-28` but answers `-32601` to a mandatory new-revision
  method, reconnect using `2025-11-25` rather than failing the server.

**Comment by awasilik** [comment]
Hi. I encountered the same problem -> though it didn't work for me ever. I am working on GitHub Copilot version Version 1.1.22

**Comment by awasilik** [comment]
Fixed in 1.2.23 :) Thanks
